### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Madji** [iicc1/TgBash#11]
When trying to install a greeting in the chat. Submitting team setwelcome . the Tex bot sends a new greeting. but in the chat when entering a new user to the chat bot just says test

**Comment by otgo** [comment]
Oh. Show me the console

**Comment by otgo** [comment]
Now TgBash is using redis-cli (installed by redis-server)
Update:
```bash
git checkout .
git pull
```

If you have yet the error, please send a issue to https://github.com/antirez/redis, they can help you :)
