### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by Madji** [iicc1/TgBash#9]
./bot.sh
BOT STARTED IN NORMAL SESSION 
@test_bot  
jq: error: Cannot index array with string
 failed to connect to server  
failed to connect to server  
 /info
PRIVATE || ID 184370179 | User @user | Firstname name  | Lastname name  
Fri Sep 9 22:24:37 MSK 2016
failed to connect to server

**Comment by otgo** [comment]
Do you have the settings in config.sh? Your id; token; lang

**Comment by Madji** [comment]
Perevodbot:
Yes of course, I entered all data in settings.
Perevodbot:
the bot is not working correctly. and after executing any commands that appear these errors. I didn't touch the source code. installed according to instructions. installed dependencies. redis should, too.

**Comment by Madji** [comment]
bot attracted me easy to adapt and easy. I need a simple bot to execute my commands on the server(because of scripts).
messed up the button

**Comment by Madji** [comment]
![screenshot_2016-09-10-11-04-28](https://cloud.githubusercontent.com/assets/2238714/18408961/dbd5e132-774e-11e6-88c7-e83394972ec5.png)
![screenshot_2016-09-10-11-04-36](https://cloud.githubusercontent.com/assets/2238714/18408966/e8af5fdc-774e-11e6-9daa-44fdc033b808.png)

**Comment by otgo** [comment]
That's normal because the command /getinfo is by reply.
I'll fix that, i dont have that error but probably that's problem of redis server

**Comment by Madji** [comment]
I realized I have a problem with redis server? clear. if prompt in what side to dig, I'd appreciate it. since other units require a redis problem not expressed.
